apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: bun-hono-react
  labels:
    app: monorepo
    component: client
spec:
  type: LoadBalancer
  selector:
    app: monorepo
    component: client
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
  sessionAffinity: None
